# Generated by Django 3.0 on 2021-05-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('car_model', models.CharField(max_length=64)),
                ('car_year', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
    ]
