# Generated by Django 3.0 on 2021-06-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='image',
            field=models.FileField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
